# Generated by Django 5.0.3 on 2024-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatedmaps', '0002_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
