# Generated by Django 5.0.3 on 2024-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatedmaps', '0003_alter_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
