# Generated by Django 5.0.3 on 2024-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatedmaps', '0004_alter_site_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
